name = 'My Game'

modules = [
    './main',
    './gui_module',
    '@rpgjs/default-gui',
    '@rpgjs/save',
    '@rpgjs/plugin-emotion-bubbles',
    '@rpgjs/my/chat',
]

[start]
    map = 'simplemap'
    graphic = 'hero'
    hitbox = [16, 16]

[titleScreen]
    mongodb = "mongodb://localhost:27017/test"